steps:
  - id: install go package
    name: gcr.io/cloud-builders/glide
    env:
      - PROJECT_ROOT=github.com/cage1016/bonego
    args:
      - install
  - id: go test
    name: gcr.io/cloud-builders/go
    env:
      - PROJECT_ROOT=github.com/cage1016/bonego
    args:
      - test
      - '-v'
  - id: go install
    name: gcr.io/cloud-builders/go
    args:
      - install
      - '-a'
      - '-ldflags'
      - '-s'
      - '-installsuffix'
      - cgo
      - github.com/cage1016/bonego
    env:
      - PROJECT_ROOT=github.com/cage1016/bonego
      - CGO_ENABLED=0
      - GOOS=linux
  - id: create dokcer image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - gcr.io/$PROJECT_ID/bonego
      - .
images:
  - gcr.io/$PROJECT_ID/bonego
